# .github/workflows/sonarcloud.yml
name: SonarCloud
on:
  push:
    branches: [main-melhorias]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          sonar.projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar.organization: ${{ secrets.SONAR_ORGANIZATION }}
