# .github/workflows/sonarcloud.yml
name: SonarCloud
on:
  push:
    branches: [main-melhorias]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=RubenAlmeida-uab_chatbot
            -Dsonar.organization=rubenalmeida-uab
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
